@url = http://127.0.0.1:3001

###
GET {{url}}/admin

### 注册
POST {{url}}/admin/register
content-type: application/json

{
  "username": "哈哈哈",
  "email": "77988666@qq.com",
  "passwrod": "666666",
  "rold": 0,
  "status": 0
}

###登录
POST {{url}}/admin/login
content-type: application/json

{
  "username": "哈哈哈",
  "email": "6666666@qq.com",
  "passwrod": "666666",
  "rold": 0,
  "status": 0
}

###获取用户
POST {{url}}/admin/getUser
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmY3YjY1MTI3ZWZhMTA2YWMxM2E2OGMiLCJpYXQiOjE2MTAwNzQ1NzF9.a-IAGsIia6mqRRoA2tet3nTzpMNE3Gb4Voh-kAZgodU

{
  "page": 2,
  "size": 10
}

###修改用户状态
POST {{url}}/admin/setUserStatus
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmY3YjY1MTI3ZWZhMTA2YWMxM2E2OGMiLCJpYXQiOjE2MTAwNzQ1NzF9.a-IAGsIia6mqRRoA2tet3nTzpMNE3Gb4Voh-kAZgodU

{
  "id": "5ff58866e6c5f945a033741d",
  "status": 0
}